### ISSUE TITLE
Firefox XPI DownZemAll extension not installable. Why is not signed?

### ISSUE THREAD

**Issue by RafaelLinux** [setvisible/ArrowDL#103]
Firefox 110.0.1 refuses to install latest XPI extension of DownZemAll cause is not verified.

Why is not available  in Firefox extensions repository??

Thank you

**Comment by Lehnemann** [comment]
It happens with me too.

**Comment by RafaelLinux** [comment]
Ver 3.0.3
Progress bar is not updated in realtime. It's working "his way", like when you have a slow internet connection. If I download same video with another application, it shows progress bar and dowload speed in realtime.
[vokoscreenNG-2023-04-08_11-28-35.webm](https://user-images.githubusercontent.com/13048959/230714378-e1e7e139-034e-4955-9fac-257124af8f4b.webm)

**Comment by RafaelLinux** [comment]
Ver 3.0.5 .- Firefox still don't let install XPI cause is not signed :(

**Comment by trimechee** [comment]
Use Mercury brower to use unsigned extension 

https://github.com/Alex313031/Mercury

**Comment by RafaelLinux** [comment]
But that doesn't answer my question. Why not so sign the extension? It is cost anything? Till I know, you only need a cerfiticate to sign it. It's a matter of security basically.

**Comment by setvisible** [comment]
It's signed by Mozilla when I upload the XPI to AMO (addons.mozilla.org).

Download the XPI, unzip it :

https://addons.mozilla.org/fr/firefox/addon/arrow-dl/

The signatures and digests are in "META-INF".

Regards

**Comment by RafaelLinux** [comment]
Perfect!! I installed it directly even without unzipping, so were easy and without issues.
Thank you
