### ISSUE TITLE
[FR]: Twitter videos download

### ISSUE THREAD

**Issue by RafaelLinux** [setvisible/ArrowDL#112]
Hi.

While I can download videos from Pinterest, I'm not able to do it with Twitter links.

Please, could you add that feature?

**Comment by setvisible** [comment]
Hi,

It's more something to address to yt-dlp. Please feel free to post a request to the project team:

https://github.com/yt-dlp/yt-dlp

Once implemented in yt-dlp, it will be magically available in ArrowDL too!

I'll close the ticket,

Regards
