### ISSUE TITLE
Change project name in Chocolatey 

### ISSUE THREAD

**Issue by setvisible** [setvisible/ArrowDL#122]
Hi @Xav83 ,

Hope you are well,

Happy new year

Is it possible to rename:
https://community.chocolatey.org/packages/downzemall

to
https://community.chocolatey.org/packages/arrowdl

regarding the recent project name change?

Note: the link in the README.md should work back after this change.

Thanks in advance,

Regards,
SV

**Comment by Xav83** [comment]
Hi @setvisible,

Happy new year to you too :slightly_smiling_face: 

It is not possible to rename a package directly, but we can work around that.
First, I am going to **create** the package `arrowdl`.
Then, I will mark the package `downzemall` as **deprecated** and propose a **link to the new package**.

I'll create the package `arrowdl` today, and will notify you when new progress is achieved :wink:

**Comment by Xav83** [comment]
The [package arrowdl](https://community.chocolatey.org/packages/arrowdl) is now created, and in the validation process of Chocolatey. Once validated, I'll mark the package `downzemall` as deprecated :slightly_smiling_face:

**Comment by Xav83** [comment]
The version `4.0.0` of `arrowdl` has been validated and the version `4.0.1` is currently in the validation process :tada: :tada: 
So I'll soon mark the package `downzemall` as deprecated, with a link to `arrowdl` package :wink:

**Comment by setvisible** [comment]
Excellent! Thank you very much!

The README now points to the new package

Cheers,
