### ISSUE TITLE
Bugs in the portable version

### ISSUE THREAD

**Issue by forapreder** [setvisible/ArrowDL#124]
ArrowDL 4.0.0 Windows 10 x64
![1001](https://github.com/setvisible/ArrowDL/assets/60479869/2e25ea73-8950-463a-853c-44c6bba5ff76)

The portable version does not display icons. Downloaded Video and Audio streams are not combined into one file .mp4. DownZemAll did it.

**Comment by setvisible** [comment]
See https://github.com/setvisible/ArrowDL/issues/123#issuecomment-1875749157
