### ISSUE TITLE
"Couldn't parse playlist" error when trying to download video stream

### ISSUE THREAD

**Issue by RafaelLinux** [setvisible/ArrowDL#130]
Last year, I opened in "Discussions" a thread about this, but no one answered, so I ask here.
ArrowDL is not able to download media from some public websites like [this](https://ok.ru/video/5140778912363). There are more websites where ArrowDL simply show that error after pasting URL.

What's neccesary to get ArrowDL to download media properly from those kind of URL?

Thanks

**Comment by setvisible** [comment]
It better to ask **ytdlp** team to implement it.

Close because the issue is quite old.

**Comment by RafaelLinux** [comment]
Ok reported to them
