### ISSUE TITLE
主要な動画サービス以外で対応していない場合のエラーErrors when not supported by other than major video services

### ISSUE THREAD

**Issue by takuyatahata** [setvisible/ArrowDL#135]

**Comment by setvisible** [comment]
Hi

Please feel free to report this issue to the team of yt-dlp:
https://github.com/yt-dlp/yt-dlp

Once fixed by yt-dlp team, it should be magically available in ArrowDL.

I'll close the issue

Regards

**Comment by takuyatahata** [comment]
Thanks for offering.
japanese net cafe PC is super slow, so no time to try
今後も何か問題が起きれば、投稿しますが、世界中の誰かが同じことで悩んでいるので、重複の話題になるのであれば、表示されるような機能がGITHUB上に欲しいです。忘れていて同じことを何度も聞くかもしれません。ごめんなさい。
