### ISSUE TITLE
ArrowDL 4.0.1 can't download any video from YouTube!

### ISSUE THREAD

**Issue by PCUser2021** [setvisible/ArrowDL#144]
Windows 11 Home. (Everything is updated to the latest version)
Try any link and paste it on the ADL and download the file, like this:
https://www.youtube.com/watch?v=CDl9ZMfj6aE&pp=ygUeYWxpZW4gYW50IGZhcm0gc21vb3RoIGNyaW1pbmFs

**Comment by setvisible** [comment]
Hi,

It works on my side.

Maybe do *Help* > *Check updates* to be sure to use the last ytdlp version 2024.08.06
 
Then try it again. If still not working, please copy-paste the logs:
Right-clic (or *View*) > *Download Information* (Alt-I) > *Messages* 

Regards

**Comment by setvisible** [comment]
Close as can't reproduce

**Comment by setvisible** [comment]
Close as can't reproduce
