### ISSUE TITLE
How do I get ArrowDL to actively take over the download function of my browser? 

### ISSUE THREAD

**Issue by sr79368142** [setvisible/ArrowDL#151]
Man, I installed ArrowDL's browser plugin, but still can't take over the browser, this problem has been bothering me all day! ArrowDL is a great program, meets all my requirements for a downloader, doesn't need to be installed, doesn't write file notes and download information into the registry, for me, he is the best idm alternative, if I can solve the ArrowDL's active takeover of the browser, this software would be even better!

Translated with DeepL.com (free version)

**Comment by setvisible** [comment]
ArrowDL is compatible with latest versions of Chome, Edge and Firefox.

The extension is available in the respective addon markets:

- https://chromewebstore.google.com/
- https://microsoftedge.microsoft.com/addons/detail/arrowdl/dncbgpeljmbgmohpfbhpaieglgkplbfj
- https://addons.mozilla.org/fr/firefox/addon/arrow-dl/

There's no plan to extend to other browsers at the moment;

Cheers

**Comment by setvisible** [comment]
ArrowDL is compatible with latest versions of Chome, Edge and Firefox.

The extension is available in the respective addon markets:

- https://chromewebstore.google.com/
- https://microsoftedge.microsoft.com/addons/detail/arrowdl/dncbgpeljmbgmohpfbhpaieglgkplbfj
- https://addons.mozilla.org/fr/firefox/addon/arrow-dl/

There's no plan to extend to other browsers at the moment;

Cheers

**Comment by sr79368142** [comment]
Dear @setvisible  , what I mean is that I would like ArrowDL to take over the download from the browser in a similar way to IDM or FDM, i.e. after clicking on the download link, ArrowDL running in the background monitors the link and pops up the main window.
Instead of clicking on the download link in the browser and then clicking on the save link on the right button to call ArrowDL to download, which is very troublesome.
Because in some download links which can't capture the file name, such as the download links of various online disks, it will download the file as job.php and prompt “3xx Redirect remote host closed”. However, this does not happen with other download managers that can take over actively.
I would also like to add the option to have a dialog box that pops up to start the download when actively taking over the download, so that I can add notes or make other changes.
ArrowDL's support for file notes is great, but I don't see an option to add a column to show notes when I right-click on a column header, nor do I see an entry to support searching.
Also, during my trial, I found that ArrowDL does not delete files. I right-clicked on a downloaded file to delete it, but it did not work, and I can still see the downloaded file in Explorer or File Manager.
