### ISSUE TITLE
Zip partial download

### ISSUE THREAD

**Issue by Tarek-Hasan** [setvisible/ArrowDL#152]
Please, add support for partial downloading of a zip file.

**Comment by setvisible** [comment]
Hi,

Please share more examples and explanation about this need.

indeed it's a lot of work to add a new feature, it's important to verify if the result is worse the effort.

Thanks,

Regards

**Comment by Tarek-Hasan** [comment]
Zip partial download is selecting which file to download from inside a zip file, like what we can do when downloading torrent. Older FDM version v3.x (back when it was open source) could do that. You can look into its [source code](https://sourceforge.net/p/freedownload/code/HEAD/tree/) for reference.
