### ISSUE TITLE
Does not run in Windows 7

### ISSUE THREAD

**Issue by southern-boy** [setvisible/ArrowDL#156]
I tried to run compile.bat after modifying the install path.  There was no setup executable to existing or available to rename. So I went to the web site and downloaded the Windows 64 bit installer executable and ran it.  It appeared to install ok but running the application returns an error 
"The procedure entry point CreateEventW could not be located in dynamic link library api-ms-win-core-synch-I1-2-0.dll" and fails.  I assume it is because it is being installed on Windows 7 but I did not see the OS requirement listed.

Thank you.
![ArrowDL_run_error](https://github.com/user-attachments/assets/1406c2d0-39eb-4d1d-b942-c5baed7944b6)

**Comment by setvisible** [comment]
Hi,

Windows 7 is not supported by Microsoft anymore (since 2020). That is, bugs are likely to happen, 3rd-party libraries like Qt aren't maintained for this version:

https://forum.qt.io/topic/140132/does-qt6-built-applications-run-on-windows-7

I'll close the ticket.

Regards
